### ISSUE TITLE
Cloud-Mining-BTC, SoloMiner.py not executing

### ISSUE THREAD

**Issue by BoiledEggPie** [NearZeK/Cloud-Mining-BTC#1]
![image](https://github.com/NearZeK/Cloud-Mining-BTC/assets/129612640/c67a01d9-289c-464d-8a46-ee97a6824a25)
![image](https://github.com/NearZeK/Cloud-Mining-BTC/assets/129612640/ee83b10b-5eec-4f5b-8418-a9e9ac562039)
I get an error claiming to not being able to import '__init__.py' from modules, and indicates the error is in line 12, where the code is blank.

**Comment by luannnn** [comment]
The same for me
